# coding: utf-8

# flake8: noqa
"""
    GeoServer Settings

    The Settings area shows global configuration for the server  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from gs_rest_api_settings.model.contact import Contact
from gs_rest_api_settings.model.coverage_access import CoverageAccess
from gs_rest_api_settings.model.jai import JAI
from gs_rest_api_settings.model.model_global import ModelGlobal
from gs_rest_api_settings.model.settings import Settings
from gs_rest_api_settings.model.workspace_contact import WorkspaceContact
from gs_rest_api_settings.model.workspace_settings import WorkspaceSettings
