# coding: utf-8

# flake8: noqa
"""
    OWS Services

    An OWS service refers to any of the OGC services that GeoServer supports, such as WFS, WMS, and WCS. These endpoints controls the settings of these services.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from gs_rest_api_owsservices.model.wcs_info import WCSInfo
from gs_rest_api_owsservices.model.wcs_info_wrapper import WCSInfoWrapper
from gs_rest_api_owsservices.model.wfs_info import WFSInfo
from gs_rest_api_owsservices.model.wfs_info_wrapper import WFSInfoWrapper
from gs_rest_api_owsservices.model.wms_info import WMSInfo
from gs_rest_api_owsservices.model.wms_info_wrapper import WMSInfoWrapper
from gs_rest_api_owsservices.model.wmts_info import WMTSInfo
from gs_rest_api_owsservices.model.wmts_info_wrapper import WMTSInfoWrapper
