# coding: utf-8

"""
    GeoServer Coverages

    A coverage is a raster data set which originates from a coverage store.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_coverages
from model.coverage_info import CoverageInfo  # noqa: E501
from gs_rest_api_coverages.rest import ApiException


class TestCoverageInfo(unittest.TestCase):
    """CoverageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCoverageInfo(self):
        """Test CoverageInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_coverages.models.coverage_info.CoverageInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
