# coding: utf-8

"""
    GeoServer Coverages

    A coverage is a raster data set which originates from a coverage store.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_coverages
from api.default_api import DefaultApi  # noqa: E501
from gs_rest_api_coverages.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_coverage(self):
        """Test case for delete_coverage

        """
        pass

    def test_delete_coverage_store(self):
        """Test case for delete_coverage_store

        """
        pass

    def test_delete_workspace_coverage(self):
        """Test case for delete_workspace_coverage

        """
        pass

    def test_delete_workspace_coverage_store(self):
        """Test case for delete_workspace_coverage_store

        """
        pass

    def test_get_coverage(self):
        """Test case for get_coverage

        """
        pass

    def test_get_coverage_store(self):
        """Test case for get_coverage_store

        """
        pass

    def test_get_workspace_coverage(self):
        """Test case for get_workspace_coverage

        """
        pass

    def test_get_workspace_coverage_store(self):
        """Test case for get_workspace_coverage_store

        """
        pass

    def test_post_coverage(self):
        """Test case for post_coverage

        """
        pass

    def test_post_coverage_store(self):
        """Test case for post_coverage_store

        """
        pass

    def test_post_workspace_coverage(self):
        """Test case for post_workspace_coverage

        """
        pass

    def test_post_workspace_coverage_store(self):
        """Test case for post_workspace_coverage_store

        """
        pass

    def test_put_coverage(self):
        """Test case for put_coverage

        """
        pass

    def test_put_coverage_store(self):
        """Test case for put_coverage_store

        """
        pass

    def test_put_workspace_coverage(self):
        """Test case for put_workspace_coverage

        """
        pass

    def test_put_workspace_coverage_store(self):
        """Test case for put_workspace_coverage_store

        """
        pass


if __name__ == '__main__':
    unittest.main()
