# coding: utf-8

"""
    GeoServer Coverages

    A coverage is a raster data set which originates from a coverage store.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_coverages
from model.metadata_entry import MetadataEntry  # noqa: E501
from gs_rest_api_coverages.rest import ApiException


class TestMetadataEntry(unittest.TestCase):
    """MetadataEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadataEntry(self):
        """Test MetadataEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_coverages.models.metadata_entry.MetadataEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
