# coding: utf-8

"""
    OWS Services

    An OWS service refers to any of the OGC services that GeoServer supports, such as WFS, WMS, and WCS. These endpoints controls the settings of these services.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_owsservices
from model.wms_info_wrapper import WMSInfoWrapper  # noqa: E501
from gs_rest_api_owsservices.rest import ApiException


class TestWMSInfoWrapper(unittest.TestCase):
    """WMSInfoWrapper unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWMSInfoWrapper(self):
        """Test WMSInfoWrapper"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_owsservices.models.wms_info_wrapper.WMSInfoWrapper()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
