# coding: utf-8

# flake8: noqa
"""
    GeoServer Data Stores

    A data store contains vector format spatial data. It can be a file (such as a shapefile), a database (such as PostGIS), or a server (such as a remote Web Feature Service).  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from gs_rest_api_datastores.model.datastore import Datastore
from gs_rest_api_datastores.model.entry import Entry
from gs_rest_api_datastores.model.workspace import Workspace
