# coding: utf-8

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_workspaces
from model.workspace import Workspace  # noqa: E501
from gs_rest_api_workspaces.rest import ApiException


class TestWorkspace(unittest.TestCase):
    """Workspace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspace(self):
        """Test Workspace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_workspaces.models.workspace.Workspace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
