# coding: utf-8

"""
    GeoServer Layers

    A layer is a published resource (feature type or coverage).  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_layers
from model.layers import Layers  # noqa: E501
from gs_rest_api_layers.rest import ApiException


class TestLayers(unittest.TestCase):
    """Layers unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLayers(self):
        """Test Layers"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_layers.models.layers.Layers()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
