# coding: utf-8

"""
    GeoWebCache GridSets

    A Grid Set is a set of tile grids associated with a coordinate reference system.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_gwcgridsets
from model.grid_set import GridSet  # noqa: E501
from gs_rest_api_gwcgridsets.rest import ApiException


class TestGridSet(unittest.TestCase):
    """GridSet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGridSet(self):
        """Test GridSet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_gwcgridsets.models.grid_set.GridSet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
