# coding: utf-8

"""
    GeoServer CoverageStores

    A coverage store describes how access a raster data source.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_coveragestores
from api.default_api import DefaultApi  # noqa: E501
from gs_rest_api_coveragestores.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_coverage_store(self):
        """Test case for delete_coverage_store

        Delete coverage store  # noqa: E501
        """
        pass

    def test_delete_coverage_store_upload(self):
        """Test case for delete_coverage_store_upload

        """
        pass

    def test_delete_coverage_stores(self):
        """Test case for delete_coverage_stores

        """
        pass

    def test_get_coverage_store(self):
        """Test case for get_coverage_store

        Get a coverage store named {store} in the {workspace} workspace  # noqa: E501
        """
        pass

    def test_get_coverage_store_upload(self):
        """Test case for get_coverage_store_upload

        """
        pass

    def test_get_coverage_stores(self):
        """Test case for get_coverage_stores

        Get a list of all coverage stores in {workspace}  # noqa: E501
        """
        pass

    def test_post_coverage_store(self):
        """Test case for post_coverage_store

        """
        pass

    def test_post_coverage_store_upload(self):
        """Test case for post_coverage_store_upload

        """
        pass

    def test_post_coverage_stores(self):
        """Test case for post_coverage_stores

        Add a new coverage store  # noqa: E501
        """
        pass

    def test_put_coverage_store(self):
        """Test case for put_coverage_store

        Modify a single coverage store.  # noqa: E501
        """
        pass

    def test_put_coverage_store_upload(self):
        """Test case for put_coverage_store_upload

        Creates or overwrites the files for a coverage store  # noqa: E501
        """
        pass

    def test_put_coverage_stores(self):
        """Test case for put_coverage_stores

        """
        pass


if __name__ == '__main__':
    unittest.main()
