# coding: utf-8

"""
    GeoServer CoverageStores

    A coverage store describes how access a raster data source.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_coveragestores
from model.coverage_store_list_item import CoverageStoreListItem  # noqa: E501
from gs_rest_api_coveragestores.rest import ApiException


class TestCoverageStoreListItem(unittest.TestCase):
    """CoverageStoreListItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCoverageStoreListItem(self):
        """Test CoverageStoreListItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_coveragestores.models.coverage_store_list_item.CoverageStoreListItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
