# coding: utf-8

# flake8: noqa

"""
    GeoServer StructuredCoverageStores

    A structured coverage store allows description of its \"granules\" and management of them.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from gs_rest_api_structuredcoverages.api.default_api import DefaultApi
# import ApiClient
from gs_rest_api_structuredcoverages.api_client import ApiClient
from gs_rest_api_structuredcoverages.configuration import Configuration
# import models into sdk package
from gs_rest_api_structuredcoverages.model.attribute import Attribute
from gs_rest_api_structuredcoverages.model.schema import Schema
