# coding: utf-8

"""
    GeoServer XSLT transforms

    A transform contains a style sheet that can be used to generate a new textual output format of user choosing for WFS  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_transforms
from model.transform_list_item import TransformListItem  # noqa: E501
from gs_rest_api_transforms.rest import ApiException


class TestTransformListItem(unittest.TestCase):
    """TransformListItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransformListItem(self):
        """Test TransformListItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_transforms.models.transform_list_item.TransformListItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
