# coding: utf-8

"""
    GeoWebCache Blobstores

    BlobStores configure the persistance of tile data.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_gwcblobstores
from model.blob_store_reference import BlobStoreReference  # noqa: E501
from gs_rest_api_gwcblobstores.rest import ApiException


class TestBlobStoreReference(unittest.TestCase):
    """BlobStoreReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlobStoreReference(self):
        """Test BlobStoreReference"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_gwcblobstores.models.blob_store_reference.BlobStoreReference()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
