# coding: utf-8

"""
    GeoServer Security

    The Security area shows access rules and other configuration for the security subsystem  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_security
from model.acl_services import ACLServices  # noqa: E501
from gs_rest_api_security.rest import ApiException


class TestACLServices(unittest.TestCase):
    """ACLServices unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testACLServices(self):
        """Test ACLServices"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_security.models.acl_services.ACLServices()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
