# coding: utf-8

# flake8: noqa

"""
    GeoWebCache Bounds

    A RESTful interface through which get the bounds of a given layer based on srs.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from gs_rest_api_gwcbounds.api.default_api import DefaultApi
# import ApiClient
from gs_rest_api_gwcbounds.api_client import ApiClient
from gs_rest_api_gwcbounds.configuration import Configuration
# import models into sdk package
