# coding: utf-8

"""
    GeoServer Settings

    The Settings area shows global configuration for the server  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_settings
from model.coverage_access import CoverageAccess  # noqa: E501
from gs_rest_api_settings.rest import ApiException


class TestCoverageAccess(unittest.TestCase):
    """CoverageAccess unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCoverageAccess(self):
        """Test CoverageAccess"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_settings.models.coverage_access.CoverageAccess()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
