# coding: utf-8

# flake8: noqa
"""
    GeoWebCache Seeding and Truncating

    A layer is a published resource (feature type or coverage).  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from gs_rest_api_gwcseed.model.seed_request import SeedRequest
