# coding: utf-8

# flake8: noqa

"""
    GeoServer Parameter Extractor

    A parameter extractor rule allows specific request parameters as URL path fragments instead of using the query string. A echo parameter makes sure that certain URL paratemers are added to the capabilities documents backlinks.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from gs_rest_api_params-extractor.api.default_api import DefaultApi
# import ApiClient
from gs_rest_api_params-extractor.api_client import ApiClient
from gs_rest_api_params-extractor.configuration import Configuration
# import models into sdk package
from gs_rest_api_params-extractor.model.echo_parameter import EchoParameter
from gs_rest_api_params-extractor.model.echo_parameters import EchoParameters
from gs_rest_api_params-extractor.model.rule import Rule
from gs_rest_api_params-extractor.model.rules import Rules
