# coding: utf-8

# flake8: noqa

"""
    GeoServer Template

    Manage templates used to configure output (for example GetFeatureInfo reponse). Templates can be registered for the entire server or workspace. You can also configure a template for use with a store, featureType or coverage.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from gs_rest_api_templates.api.default_api import DefaultApi
# import ApiClient
from gs_rest_api_templates.api_client import ApiClient
from gs_rest_api_templates.configuration import Configuration
# import models into sdk package
from gs_rest_api_templates.model.template_reference import TemplateReference
from gs_rest_api_templates.model.templates import Templates
