# coding: utf-8

# flake8: noqa
"""
    Roles

    Organisation of security roles  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from gs_rest_api_roles.model.role import Role
from gs_rest_api_roles.model.roles import Roles
