# coding: utf-8

"""
    GeoWebCache Mass Truncate

    The REST API for mass truncation provides a mechanism for completely clearing caches more conveniently than with the seeding system  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_gwcmasstruncate
from api.default_api import DefaultApi  # noqa: E501
from gs_rest_api_gwcmasstruncate.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_masstruncate_get(self):
        """Test case for masstruncate_get

        Returns available request types for truncation  # noqa: E501
        """
        pass

    def test_masstruncate_post(self):
        """Test case for masstruncate_post

        Issue a mass truncate request  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
