# coding: utf-8

"""
    GeoServer Fonts

    A font is a set of characters that can be used in a style for displaying labels.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_fonts
from api.default_api import DefaultApi  # noqa: E501
from gs_rest_api_fonts.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_fonts(self):
        """Test case for delete_fonts

        """
        pass

    def test_get_fonts(self):
        """Test case for get_fonts

        Get a list of fonts  # noqa: E501
        """
        pass

    def test_post_fonts(self):
        """Test case for post_fonts

        """
        pass

    def test_put_fonts(self):
        """Test case for put_fonts

        """
        pass


if __name__ == '__main__':
    unittest.main()
