# coding: utf-8

# flake8: noqa

"""
    GeoServer CoverageStores

    A coverage store describes how access a raster data source.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from gs_rest_api_coveragestores.api.default_api import DefaultApi
# import ApiClient
from gs_rest_api_coveragestores.api_client import ApiClient
from gs_rest_api_coveragestores.configuration import Configuration
# import models into sdk package
from gs_rest_api_coveragestores.model.coverage_store_info import CoverageStoreInfo
from gs_rest_api_coveragestores.model.coverage_store_list import CoverageStoreList
