# coding: utf-8

"""
    GeoWebCache Global

    Global configuration for the GeoWebCache server  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_gwcglobal
from api.default_api import DefaultApi  # noqa: E501
from gs_rest_api_gwcglobal.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_global_get(self):
        """Test case for global_get

        Retrieve the global server configuration  # noqa: E501
        """
        pass

    def test_global_put(self):
        """Test case for global_put

        Modifies the global configuration.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
