# coding: utf-8

"""
    GeoServer Template

    Manage templates used to configure output (for example GetFeatureInfo reponse). Templates can be registered for the entire server or workspace. You can also configure a template for use with a store, featureType or coverage.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_templates
from model.templates import Templates  # noqa: E501
from gs_rest_api_templates.rest import ApiException


class TestTemplates(unittest.TestCase):
    """Templates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTemplates(self):
        """Test Templates"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_templates.models.templates.Templates()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
