# coding: utf-8

"""
    GeoServer WMTS Stores

    A WMTS store is a store whose source is a remote WMTS. Also known as \"Cascading WMTS\".  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_wmtsstores
from model.wmts_store_info import WMTSStoreInfo  # noqa: E501
from gs_rest_api_wmtsstores.rest import ApiException


class TestWMTSStoreInfo(unittest.TestCase):
    """WMTSStoreInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWMTSStoreInfo(self):
        """Test WMTSStoreInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_wmtsstores.models.wmts_store_info.WMTSStoreInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
