# coding: utf-8

"""
    GeoServer WMS Store Layers

    A WMS store is a store whose source is another WMS. Also known as \"Cascading WMS\" or \"External WMS\". A WMS store layer is a layer from this store.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_wmslayers
from api.default_api import DefaultApi  # noqa: E501
from gs_rest_api_wmslayers.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_wms_store_layer(self):
        """Test case for delete_wms_store_layer

        """
        pass

    def test_delete_wms_store_layers(self):
        """Test case for delete_wms_store_layers

        """
        pass

    def test_delete_wms_store_store_layer(self):
        """Test case for delete_wms_store_store_layer

        """
        pass

    def test_delete_wms_store_store_layers(self):
        """Test case for delete_wms_store_store_layers

        """
        pass

    def test_get_wms_store_layer(self):
        """Test case for get_wms_store_layer

        """
        pass

    def test_get_wms_store_layers(self):
        """Test case for get_wms_store_layers

        """
        pass

    def test_get_wms_store_store_layer(self):
        """Test case for get_wms_store_store_layer

        """
        pass

    def test_get_wms_store_store_layers(self):
        """Test case for get_wms_store_store_layers

        """
        pass

    def test_post_wms_store_layer(self):
        """Test case for post_wms_store_layer

        """
        pass

    def test_post_wms_store_layers(self):
        """Test case for post_wms_store_layers

        """
        pass

    def test_post_wms_store_store_layer(self):
        """Test case for post_wms_store_store_layer

        """
        pass

    def test_post_wms_store_store_layers(self):
        """Test case for post_wms_store_store_layers

        """
        pass

    def test_put_wms_store_layer(self):
        """Test case for put_wms_store_layer

        """
        pass

    def test_put_wms_store_layers(self):
        """Test case for put_wms_store_layers

        """
        pass

    def test_put_wms_store_store_layer(self):
        """Test case for put_wms_store_store_layer

        """
        pass

    def test_put_wms_store_store_layers(self):
        """Test case for put_wms_store_store_layers

        """
        pass


if __name__ == '__main__':
    unittest.main()
