# coding: utf-8

# flake8: noqa
"""
    GeoServer Resources

    A resource is any item in the data directory that does not represent configuration. Typical resources include styles and icons.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from gs_rest_api_resource.model.resource_directory import ResourceDirectory
from gs_rest_api_resource.model.resource_metadata import ResourceMetadata
