# coding: utf-8

# flake8: noqa

"""
    GeoServer WMS Store Layers

    A WMS store is a store whose source is another WMS. Also known as \"Cascading WMS\" or \"External WMS\". A WMS store layer is a layer from this store.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from gs_rest_api_wmslayers.api.default_api import DefaultApi
# import ApiClient
from gs_rest_api_wmslayers.api_client import ApiClient
from gs_rest_api_wmslayers.configuration import Configuration
# import models into sdk package
from gs_rest_api_wmslayers.model.metadata_entry import MetadataEntry
from gs_rest_api_wmslayers.model.style_info import StyleInfo
from gs_rest_api_wmslayers.model.wms_store_layer_info import WMSStoreLayerInfo
from gs_rest_api_wmslayers.model.wms_store_layers_available_list import WMSStoreLayersAvailableList
from gs_rest_api_wmslayers.model.wms_store_layers_list import WMSStoreLayersList
