# coding: utf-8

# flake8: noqa
"""
    GeoServer WMTS Stores

    A WMTS store is a store whose source is a remote WMTS. Also known as \"Cascading WMTS\".  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from gs_rest_api_wmtsstores.model.wmts_store_info import WMTSStoreInfo
from gs_rest_api_wmtsstores.model.wmts_stores_list import WMTSStoresList
from gs_rest_api_wmtsstores.model.wmts_stores_list_item import WMTSStoresListItem
