# coding: utf-8

"""
    GeoServer System Status

    Request provides details about OWS and REST requests that GeoServer has handled  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_system-status
from model.metrics import Metrics  # noqa: E501
from gs_rest_api_system-status.rest import ApiException


class TestMetrics(unittest.TestCase):
    """Metrics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetrics(self):
        """Test Metrics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_system-status.models.metrics.Metrics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
