# coding: utf-8

"""
    Users and Groups

    Organisation of security users and groups  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_usergroup
from api.default_api import DefaultApi  # noqa: E501
from gs_rest_api_usergroup.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_group_default_delete(self):
        """Test case for group_default_delete

        Delete a group  # noqa: E501
        """
        pass

    def test_group_default_post(self):
        """Test case for group_default_post

        Add a group  # noqa: E501
        """
        pass

    def test_group_delete(self):
        """Test case for group_delete

        Delete a group  # noqa: E501
        """
        pass

    def test_group_post(self):
        """Test case for group_post

        Add a group  # noqa: E501
        """
        pass

    def test_groups_default_get(self):
        """Test case for groups_default_get

        Query all groups  # noqa: E501
        """
        pass

    def test_groups_get(self):
        """Test case for groups_get

        Query all groups  # noqa: E501
        """
        pass

    def test_user_default_delete(self):
        """Test case for user_default_delete

        Delete a user  # noqa: E501
        """
        pass

    def test_user_default_get(self):
        """Test case for user_default_get

        Query a user  # noqa: E501
        """
        pass

    def test_user_default_post(self):
        """Test case for user_default_post

        Modify a user  # noqa: E501
        """
        pass

    def test_user_delete(self):
        """Test case for user_delete

        Delete a user  # noqa: E501
        """
        pass

    def test_user_get(self):
        """Test case for user_get

        Query a user  # noqa: E501
        """
        pass

    def test_user_post(self):
        """Test case for user_post

        Modify a user  # noqa: E501
        """
        pass

    def test_users_default_get(self):
        """Test case for users_default_get

        Query all users  # noqa: E501
        """
        pass

    def test_users_default_post(self):
        """Test case for users_default_post

        Add a new user  # noqa: E501
        """
        pass

    def test_users_get(self):
        """Test case for users_get

        Query all users  # noqa: E501
        """
        pass

    def test_users_post(self):
        """Test case for users_post

        Add a new user  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
