# coding: utf-8

"""
    Users and Groups

    Organisation of security users and groups  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_usergroup
from model.users import Users  # noqa: E501
from gs_rest_api_usergroup.rest import ApiException


class TestUsers(unittest.TestCase):
    """Users unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUsers(self):
        """Test Users"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_usergroup.models.users.Users()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
