# coding: utf-8

"""
    Roles

    Organisation of security roles  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_roles
from model.roles import Roles  # noqa: E501
from gs_rest_api_roles.rest import ApiException


class TestRoles(unittest.TestCase):
    """Roles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoles(self):
        """Test Roles"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_roles.models.roles.Roles()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
