# coding: utf-8

"""
    GeoWebCache Filter Update

    The REST API for Updating GWC filter  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_gwcfilterupdate
from model.request_filter_update import RequestFilterUpdate  # noqa: E501
from gs_rest_api_gwcfilterupdate.rest import ApiException


class TestRequestFilterUpdate(unittest.TestCase):
    """RequestFilterUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestFilterUpdate(self):
        """Test RequestFilterUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_gwcfilterupdate.models.request_filter_update.RequestFilterUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
