# coding: utf-8

"""
    GeoServer monitoring requests

    Request provides details about OWS and REST requests that GeoServer has handled  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_monitoring
from api.default_api import DefaultApi  # noqa: E501
from gs_rest_api_monitoring.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_monitor_request(self):
        """Test case for delete_monitor_request

        """
        pass

    def test_delete_monitor_requests(self):
        """Test case for delete_monitor_requests

        """
        pass

    def test_get_monitor_request(self):
        """Test case for get_monitor_request

        Get a list of requests  # noqa: E501
        """
        pass

    def test_get_monitor_requests(self):
        """Test case for get_monitor_requests

        Get a list of requests  # noqa: E501
        """
        pass

    def test_post_monitor_request(self):
        """Test case for post_monitor_request

        """
        pass

    def test_post_monitor_requests(self):
        """Test case for post_monitor_requests

        """
        pass

    def test_put_monitor_request(self):
        """Test case for put_monitor_request

        """
        pass

    def test_put_monitor_requests(self):
        """Test case for put_monitor_requests

        """
        pass


if __name__ == '__main__':
    unittest.main()
