# coding: utf-8

"""
    GeoServer monitoring requests

    Request provides details about OWS and REST requests that GeoServer has handled  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_monitoring
from model.request_list import RequestList  # noqa: E501
from gs_rest_api_monitoring.rest import ApiException


class TestRequestList(unittest.TestCase):
    """RequestList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRequestList(self):
        """Test RequestList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_monitoring.models.request_list.RequestList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
