# coding: utf-8

"""
    GeoServer StructuredCoverageStores

    A structured coverage store allows description of its \"granules\" and management of them.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_structuredcoverages
from api.default_api import DefaultApi  # noqa: E501
from gs_rest_api_structuredcoverages.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_coverage_stores(self):
        """Test case for delete_coverage_stores

        """
        pass

    def test_delete_structured_coverage_granule(self):
        """Test case for delete_structured_coverage_granule

        """
        pass

    def test_delete_structured_coverage_granules(self):
        """Test case for delete_structured_coverage_granules

        """
        pass

    def test_get_structured_coverage_granule(self):
        """Test case for get_structured_coverage_granule

        Get the attributes of a particular granule  # noqa: E501
        """
        pass

    def test_get_structured_coverage_granules(self):
        """Test case for get_structured_coverage_granules

        Get the attributes associated to the granules  # noqa: E501
        """
        pass

    def test_get_structured_coverage_index(self):
        """Test case for get_structured_coverage_index

        Get the information schema attached to the granules  # noqa: E501
        """
        pass

    def test_post_structured_coverage_granule(self):
        """Test case for post_structured_coverage_granule

        """
        pass

    def test_post_structured_coverage_granules(self):
        """Test case for post_structured_coverage_granules

        """
        pass

    def test_post_structured_coverage_index(self):
        """Test case for post_structured_coverage_index

        """
        pass

    def test_put_structured_coverage_granule(self):
        """Test case for put_structured_coverage_granule

        """
        pass

    def test_put_structured_coverage_granules(self):
        """Test case for put_structured_coverage_granules

        """
        pass

    def test_put_structured_coverage_index(self):
        """Test case for put_structured_coverage_index

        """
        pass


if __name__ == '__main__':
    unittest.main()
