# coding: utf-8

# flake8: noqa

"""
    GeoServer Namespace

    A namespace is a uniquely identifiable grouping of feature types. It is identified by a prefix and a URI.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from gs_rest_api_namespaces.api.default_api import DefaultApi
# import ApiClient
from gs_rest_api_namespaces.api_client import ApiClient
from gs_rest_api_namespaces.configuration import Configuration
# import models into sdk package
from gs_rest_api_namespaces.model.namespace import Namespace
from gs_rest_api_namespaces.model.namespace_response import NamespaceResponse
from gs_rest_api_namespaces.model.namespaces_response import NamespacesResponse
