# coding: utf-8

"""
    GeoWebCache Seeding and Truncating

    A layer is a published resource (feature type or coverage).  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_gwcseed
from model.seed_request import SeedRequest  # noqa: E501
from gs_rest_api_gwcseed.rest import ApiException


class TestSeedRequest(unittest.TestCase):
    """SeedRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSeedRequest(self):
        """Test SeedRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_gwcseed.models.seed_request.SeedRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
