# coding: utf-8

"""
    GeoWebCache Memory Cache Statistics

    A response contains memory cache statistics  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_gwcmemorycachestatistics
from api.default_api import DefaultApi  # noqa: E501
from gs_rest_api_gwcmemorycachestatistics.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_statistics_get(self):
        """Test case for statistics_get

        Returns XML or JSON response with memory cache statistics  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
