# coding: utf-8

"""
    GeoServer Manifests API

    GeoServer provides a REST service to expose a listing of all loaded JARs and resources on the running instance. This is useful for bug reports and to keep track of extensions deployed into the application.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_manifests
from api.default_api import DefaultApi  # noqa: E501
from gs_rest_api_manifests.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_about_status_get(self):
        """Test case for about_status_get

        """
        pass

    def test_about_version_get(self):
        """Test case for about_version_get

        """
        pass

    def test_get_manifest(self):
        """Test case for get_manifest

        """
        pass


if __name__ == '__main__':
    unittest.main()
