# coding: utf-8

# flake8: noqa

"""
    GeoServer Workspace

    A workspace is a grouping of data stores. Similar to a namespace, it is used to group data that is related in some way.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from gs_rest_api_workspaces.api.default_api import DefaultApi
# import ApiClient
from gs_rest_api_workspaces.api_client import ApiClient
from gs_rest_api_workspaces.configuration import Configuration
# import models into sdk package
from gs_rest_api_workspaces.model.workspace import Workspace
from gs_rest_api_workspaces.model.workspace_response import WorkspaceResponse
from gs_rest_api_workspaces.model.workspaces_response import WorkspacesResponse
