# coding: utf-8

"""
    GeoServer Layer Groups

    A layer group is a group of layers that can be referenced as a single layer as part of a WMS request. A layer group can also be used as a container for layers.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: geoserver-users@sourceforge.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import gs_rest_api_layergroups
from model.layergroup_style import LayergroupStyle  # noqa: E501
from gs_rest_api_layergroups.rest import ApiException


class TestLayergroupStyle(unittest.TestCase):
    """LayergroupStyle unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLayergroupStyle(self):
        """Test LayergroupStyle"""
        # FIXME: construct object with mandatory attributes with example values
        # model = gs_rest_api_layergroups.models.layergroup_style.LayergroupStyle()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
